### ISSUE TITLE
Can you share the preprint version of the paper?

### ISSUE THREAD

**Issue by chandlerbing65nm** [johnmartinsson/differentiable-mel-spectrogram#5]
As the title goes, can you upload here the preprint version or upload it in arxiv?

**Comment by johnmartinsson** [comment]
Sorry, I missed this. I'm planning to upload pre-prints for all my papers on my website. But have not done that yet. I'll link to them in the repos when that has been done.

**Comment by johnmartinsson** [comment]
I'll send an email with the paper to you for now.

**Comment by johnmartinsson** [comment]
There is now a link to the paper on my personal website in the README.md. From there the pre-print PDF can be downloaded. So, this issue is now considered solved.
